### ISSUE TITLE
ERROR in node_modules/screenfull/dist/screenfull.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax

### ISSUE THREAD

**Issue by Farhansarim** [sindresorhus/screenfull#192]
I'm using screeenful package in my project & facing this issue. I have tried different typescript versions. Now I'm using 
typescript ver 2.7.2
angular 6.0.3
screenfull 4.1.0
But still facing issue. Your help is highly appreciated.

**Comment by sindresorhus** [comment]
v6 no longer has the reference directive.

**Comment by Farhansarim** [comment]
> v6 no longer has the reference directive.

So what's the solution to resolve this error?
