### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by AK47-dadada** [sindresorhus/screenfull#195]
Hi, I meet below problem when using your project:

The steps are as follows:
`npm install screenfull`

`import screenfull from 'screenfull'`

And then I got an error
![image](https://user-images.githubusercontent.com/30396595/140717296-af4b9cf8-1f0f-44b6-b889-6e2b92cbeedc.png)

I wonder what the reason is

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by namnm** [comment]
@sindresorhus You can see it shows the error in this line:
`const exitFullscreenMethod = methodList?.[1];`
Which doesnt related to ESM, but optional the chaining operator `?.[1]`

**Comment by AK47-dadada** [comment]
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

![image](https://user-images.githubusercontent.com/30396595/142151086-8dcff3e5-154a-4735-8657-bffaf16bf396.png)

**Comment by adnanrafique** [comment]
Getting same issue with Angular 11. I wonder how this issue is marked as closed. Does anybody resolve it?

**Comment by AK47-dadada** [comment]
I finally found a solution:  
 
The reason is that by default babel-loader ignores all files in node_modules,  
At this point you may need to configure Webpack's babel-loader to load properly  
Please refer to https://webpack.js.org/loaders/babel-loader/  
 
So in the VueCli project, you simply configure the transpileDependencies property in vue.config.js and enter the plug-in name as a string  

`
module.exports = {
    // code
    transpileDependencies: ['screenfull']
    // code
}`

**Comment by AK47-dadada** [comment]
I finally found a solution:  
 
The reason is that by default babel-loader ignores all files in node_modules,  
At this point you may need to configure Webpack's babel-loader to load properly  
Please refer to https://webpack.js.org/loaders/babel-loader/  
 
So in the VueCli project, you simply configure the transpileDependencies property in vue.config.js and enter the plug-in name as a string  

`
module.exports = {
    // code
    transpileDependencies: ['screenfull']
    // code
}`

**Comment by AK47-dadada** [comment]
> Getting same issue with Angular 11. I wonder how this issue is marked as closed. Does anybody resolve it?

I finally found a solution:

The reason is that by default babel-loader ignores all files in node_modules,
At this point you may need to configure Webpack's babel-loader to load properly
Please refer to https://webpack.js.org/loaders/babel-loader/
