### ISSUE TITLE
Is it necessary to provide a UMD format entry file by default?

### ISSUE THREAD

**Issue by AlexRen94** [sindresorhus/screenfull#206]
As I import screenfull in a react project, the project will crash as webpack cannot import screenfull properly. I find the latest version  
provide a esm file. If I import screenfull from node_modules it won't be transpiled by babel by default. The error is as follows: 
![image](https://user-images.githubusercontent.com/38367160/156982567-cfd07a7c-63e1-4f9e-bec7-71d3b52e8f7e.png)

A possible solution is to include screenfull in webpack config so as to be transpiled by babel-loader.

As a convention a package used in browser exposes a umd format file as a entry, to name a few, style-components，ant-design. So I would recommend provide a umd  format rather than esm by default.

**Comment by sindresorhus** [comment]
> As a convention a package used in browser exposes a umd format file as a entry, to name a few, style-components，ant-design.

That's the old convention. ESM is the new way and actually better for browser usage.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by sindresorhus** [comment]
I have no plans to support UMD.

**Comment by AlexRen94** [comment]
> I have no plans to support UMD.

Anyway thanks for reply👍🏻
