### ISSUE TITLE
CJS version request

### ISSUE THREAD

**Issue by GlenHughes** [sindresorhus/screenfull#207]
Hi,

Is it possible that a **cjs** version could be added to the package? I need this to help with some unit tests I'm creating where screenfull is imported. 

Thanks in advance :)

**Comment by sindresorhus** [comment]
No plans to add CJS support. If you need CJS support, you can use the previous major version or use `await import(…)`.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
